export enum StatusCodeEnum {
  SUCCESS = 0,
  IN_PROCESS = 1,
  UNKNOWN_ERROR = -1,
  NOT_FOUND_ERROR = -2,
  WRONG_CREDENTIALS_ERROR = -3,
  VALIDATION_ERROR = -4,
  AUTHENTICATION_ERROR = -5,
  ACCESS_FORBIDDEN_ERROR = -6,
  DUPLICATE_DATA_ERROR = -7,
  BUSINESS_LOGIC_ERROR = -8,
  TOKEN_EXPIRED_ERROR = -9,
  TOKEN_NOT_VALID_ERROR = -10,
  TOKEN_REFRESH_ERROR = -11,
  GATEWAYS_QUEUE_MANAGER_ERROR = -12,
  DATABASE_ERROR = -13,
  PHONE_NUMBER_ERROR = -14
}
